# Generated by Django 6.0.3 on 2026-08-23 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(help_text='Unique asset identifier e.g. POL-EQ-001', max_length=100, unique=True)),
                ('asset_type', models.CharField(choices=[('COMPUTER', 'Computer workstation'), ('LAPTOP', 'Forensic Laptop'), ('STORAGE', 'Encrypted Hard Drive / USB'), ('VEHICLE', 'Police Vehicle'), ('WEAPON', 'Service Weapon'), ('DOCUMENT_VAULT', 'Secure Document Vault'), ('OTHER', 'Other Equipment')], default='OTHER', max_length=50)),
                ('asset_name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('IN_USE', 'In Use'), ('TRANSFERRED', 'Transferred'), ('MAINTENANCE', 'In Maintenance'), ('RETURNED', 'Returned'), ('LOST', 'Lost'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=30)),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], default='GOOD', max_length=30)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_assets', to='cases.case')),
                ('current_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assets_asset',
                'ordering': ['asset_id'],
            },
        ),
    ]
