# Generated by Django 6.0.3 on 2026-08-21 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_provider', models.CharField(default='local', max_length=50)),
                ('active_model', models.CharField(default='qwen2.5:3b', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AI Settings',
            },
        ),
        migrations.CreateModel(
            name='AuditSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_logging_enabled', models.BooleanField(default=True)),
                ('log_document_access', models.BooleanField(default=True)),
                ('log_downloads', models.BooleanField(default=True)),
                ('log_uploads', models.BooleanField(default=True)),
                ('log_metadata_changes', models.BooleanField(default=True)),
                ('log_authentication', models.BooleanField(default=True)),
                ('log_case_changes', models.BooleanField(default=True)),
                ('log_security_events', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit Settings',
            },
        ),
        migrations.CreateModel(
            name='BlockchainSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('rpc_endpoint', models.CharField(default='http://127.0.0.1:8545', max_length=255)),
                ('chain_id', models.IntegerField(default=31337)),
                ('contract_address', models.CharField(default='0x5FbDB2315678afecb367f032d93F642f64180aa3', max_length=255)),
                ('auto_anchor', models.BooleanField(default=True)),
                ('auto_verify', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blockchain Settings',
            },
        ),
        migrations.CreateModel(
            name='DocumentSecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encryption_enabled', models.BooleanField(default=True)),
                ('encryption_algorithm', models.CharField(default='AES-256 / Fernet CBC', max_length=100)),
                ('hash_verification_enabled', models.BooleanField(default=True)),
                ('signature_verification_enabled', models.BooleanField(default=True)),
                ('tamper_detection_enabled', models.BooleanField(default=True)),
                ('max_upload_size_mb', models.IntegerField(default=50)),
                ('allowed_file_types', models.CharField(default='pdf,txt,doc,docx', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Document Security Settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_alerts', models.BooleanField(default=True)),
                ('tampering_alerts', models.BooleanField(default=True)),
                ('failed_auth_alerts', models.BooleanField(default=True)),
                ('blockchain_failure_alerts', models.BooleanField(default=True)),
                ('email_notifications_enabled', models.BooleanField(default=False)),
                ('email_service_configured', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_timeout_minutes', models.IntegerField(default=60)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('lockout_duration_minutes', models.IntegerField(default=15)),
                ('require_strong_password', models.BooleanField(default=True)),
                ('require_mfa', models.BooleanField(default=False)),
                ('jwt_expiry_minutes', models.IntegerField(default=60)),
                ('allow_concurrent_sessions', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Security Settings',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='Delhi Police Cyber Crime Cell', max_length=255)),
                ('system_name', models.CharField(default='SIH26190 Digital Evidence Integrity System', max_length=255)),
                ('default_office', models.CharField(default='Connaught Place P.S.', max_length=255)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=100)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=50)),
                ('time_format', models.CharField(default='24h', max_length=50)),
                ('language', models.CharField(default='en-us', max_length=20)),
                ('items_per_page', models.IntegerField(default=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
