# Generated by Django 6.0.3 on 2026-08-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(help_text='Official case ID e.g. CASE-2026-001', max_length=100, unique=True)),
                ('fir_number', models.CharField(blank=True, help_text='FIR number if applicable', max_length=100)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('case_type', models.CharField(choices=[('CRIMINAL', 'Criminal'), ('CIVIL', 'Civil'), ('INVESTIGATION', 'Investigation'), ('COURT', 'Court Proceeding'), ('FORENSIC', 'Forensic Investigation'), ('OTHER', 'Other')], default='INVESTIGATION', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived'), ('PENDING', 'Pending')], default='ACTIVE', max_length=20)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('police_station', models.CharField(blank=True, max_length=300)),
                ('court_name', models.CharField(blank=True, max_length=300)),
                ('jurisdiction', models.CharField(blank=True, max_length=300)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'cases_case',
                'ordering': ['-created_at'],
            },
        ),
    ]
