# Generated by Django 6.0.3 on 2026-08-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='fir_number',
            field=models.CharField(blank=True, db_index=True, help_text='FIR number if applicable', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived'), ('PENDING', 'Pending')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
