# Generated by Django 6.0.3 on 2026-08-21 18:04

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_username', models.CharField(blank=True, help_text='Snapshot of username', max_length=150)),
                ('actor_role', models.CharField(blank=True, help_text='Role at time of action', max_length=20)),
                ('action', models.CharField(choices=[('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_VIEWED', 'Document Viewed'), ('DOCUMENT_DOWNLOADED', 'Document Downloaded'), ('DOCUMENT_UPDATED', 'Document Updated'), ('DOCUMENT_VERSION_CREATED', 'Document Version Created'), ('DOCUMENT_ACCESS_DENIED', 'Document Access Denied'), ('DOCUMENT_INTEGRITY_CHECK', 'Document Integrity Check'), ('DOCUMENT_SIGNED', 'Document Signed'), ('CASE_CREATED', 'Case Created'), ('CASE_ASSOCIATED', 'Case Associated'), ('SEARCH_PERFORMED', 'Search Performed'), ('USER_PERMISSION_CHANGED', 'User Permission Changed'), ('USER_LOGIN', 'User Login'), ('BLOCKCHAIN_ANCHORED', 'Blockchain Anchored'), ('SYSTEM_EVENT', 'System Event')], max_length=50)),
                ('result', models.CharField(blank=True, help_text='SUCCESS | DENIED | FAILED', max_length=50)),
                ('details', models.TextField(blank=True, help_text='Additional context')),
                ('previous_event_hash', models.CharField(blank=True, help_text='SHA-256 of previous event', max_length=64)),
                ('current_event_hash', models.CharField(blank=True, help_text='SHA-256 of this event', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'audit_event',
                'ordering': ['timestamp'],
            },
        ),
    ]
