# Generated by Django 6.0.3 on 2026-08-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_hash', models.CharField(help_text='SHA-256 hex of original document bytes', max_length=64)),
                ('tx_hash', models.CharField(blank=True, help_text='On-chain transaction hash', max_length=200)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('network', models.CharField(default='hardhat-local', max_length=100)),
                ('contract_address', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ANCHORED', 'Anchored'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('anchored_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'blockchain_anchor',
                'ordering': ['-anchored_at'],
            },
        ),
    ]
