# Generated by Django 6.0.3 on 2026-08-21 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchain', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainanchor',
            name='anchored_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_anchors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockchainanchor',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_anchors', to='documents.document'),
        ),
        migrations.AddField(
            model_name='blockchainanchor',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_anchors', to='documents.documentversion'),
        ),
    ]
