# Generated by Django 6.0.3 on 2026-08-21 18:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True)),
                ('extraction_method', models.CharField(blank=True, help_text='pdf_text | ocr_tesseract | ocr_paddleocr', max_length=50)),
                ('extraction_confidence', models.FloatField(blank=True, null=True)),
                ('extracted_case_id', models.CharField(blank=True, max_length=200)),
                ('extracted_fir_number', models.CharField(blank=True, max_length=200)),
                ('extracted_date', models.CharField(blank=True, max_length=100)),
                ('extracted_location', models.CharField(blank=True, max_length=500)),
                ('extracted_police_station', models.CharField(blank=True, max_length=500)),
                ('extracted_court_name', models.CharField(blank=True, max_length=500)),
                ('extracted_persons', models.JSONField(default=list)),
                ('extracted_organizations', models.JSONField(default=list)),
                ('extracted_legal_sections', models.JSONField(default=list)),
                ('extracted_evidence_ids', models.JSONField(default=list)),
                ('classified_type', models.CharField(blank=True, max_length=30)),
                ('classification_method', models.CharField(blank=True, help_text='rule_based | embedding | llm', max_length=50)),
                ('classification_confidence', models.FloatField(blank=True, null=True)),
                ('ai_output', models.JSONField(blank=True, default=dict)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents_metadata',
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('sha256_hash', models.CharField(help_text='SHA-256 of the original file bytes for this version', max_length=64)),
                ('storage_location', models.CharField(max_length=1000)),
                ('file_size', models.BigIntegerField()),
                ('change_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blockchain_anchored', models.BooleanField(default=False)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'documents_version',
                'ordering': ['version_number'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=500)),
                ('document_type', models.CharField(choices=[('FIR', 'First Information Report'), ('POLICE_REPORT', 'Police Report'), ('WITNESS_STATEMENT', 'Witness Statement'), ('INVESTIGATION_REPORT', 'Investigation Report'), ('CHARGE_SHEET', 'Charge Sheet'), ('EVIDENCE_RECORD', 'Evidence Record'), ('COURT_FILING', 'Court Filing'), ('FORENSIC_REPORT', 'Forensic Report'), ('LEGAL_NOTICE', 'Legal Notice'), ('JUDGMENT', 'Judgment'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField(help_text='Original file size in bytes')),
                ('storage_location', models.CharField(help_text='Encrypted file path (relative)', max_length=1000)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('sha256_hash', models.CharField(help_text='SHA-256 hex digest of original file bytes', max_length=64)),
                ('current_version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted'), ('ERROR', 'Error')], default='PROCESSING', max_length=20)),
                ('case_association_method', models.CharField(blank=True, help_text='How the document was linked: DETERMINISTIC | SEMANTIC | MANUAL', max_length=50)),
                ('case_association_confidence', models.FloatField(blank=True, help_text='Similarity score 0-1 if semantic association', null=True)),
                ('case_association_reason', models.TextField(blank=True)),
                ('signature', models.TextField(blank=True, help_text='RSA signature of SHA-256 hash in hex')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='cases.case')),
            ],
            options={
                'db_table': 'documents_document',
                'ordering': ['-created_at'],
            },
        ),
    ]
