# Generated by Django 6.0.3 on 2026-08-23 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='legal_hold_status',
            field=models.BooleanField(default=False, help_text='True if document is locked due to active court hold'),
        ),
        migrations.AddField(
            model_name='document',
            name='retention_category',
            field=models.CharField(default='STANDARD', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='retention_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='retention_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
