# Generated by Django 6.0.3 on 2026-08-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_legal_hold_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFileStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_location', models.CharField(max_length=1000, unique=True)),
                ('encrypted_data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'documents_filestore',
            },
        ),
    ]
