# Generated by Django 6.0.3 on 2026-08-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_add_documentfilestore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('FIR', 'FIR'), ('POLICE_REPORT', 'Police Report'), ('INVESTIGATION_RECORD', 'Investigation Record'), ('INVESTIGATION_REPORT', 'Investigation Report'), ('WITNESS_STATEMENT', 'Witness Statement'), ('CHARGE_SHEET', 'Charge Sheet'), ('EVIDENCE_RECORD', 'Evidence Record'), ('COURT_FILING', 'Court Filing'), ('FORENSIC_REPORT', 'Forensic Report'), ('LEGAL_NOTICE', 'Legal Notice'), ('JUDGMENT', 'Judgment'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='sha256_hash',
            field=models.CharField(db_index=True, help_text='SHA-256 hex digest of original file bytes', max_length=64),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted'), ('ERROR', 'Error')], db_index=True, default='PROCESSING', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentmetadata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='documentmetadata',
            name='extracted_fir_number',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='sha256_hash',
            field=models.CharField(db_index=True, help_text='SHA-256 of the original file bytes for this version', max_length=64),
        ),
    ]
