# Generated by Django 6.0.3 on 2026-08-24 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='retention_start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
